# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dbcd50db82925fd83eb2c8d7946bddc85139083985c73d4dc2d4fcaf34a0d097e83c2043ddbf97f5aa53dbd874605b918ea8557833c984baabebc7eae6551891

test:
  secret_key_base: 208937c5f51659c2384a8a9d26e8c198917ad23378160e27f6557c1121538d7e688cd67c5fa738649952002ac7f6cfeebdd817f6cac08fe8a50d5a273e1ee7cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
